[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.1",
    "plotly>=6.3.0",
    "streamlit>=1.48.1",
]
